"use strict";
module.exports = {
  "1": { displayName: "Article" },
  "2": { displayName: "Photo" },
  "3": { displayName: "Image" },
  "4": { displayName: "Video" },
  "5": { displayName: "Topic" },
  "6": { displayName: "Poll" },
  "7": { displayName: "Heroes Rating" },
  "8": { displayName: "Template Component Asset Map" },
  "9": { displayName: "Layout" },
  "10": { displayName: "Template" },
  "11": { displayName: "Page" },
  "12": { displayName: "External Asset" },
  "13": { displayName: "Template Component" },
  "14": { displayName: "Heroes" },
  "16": { displayName: "Advertisement" },
  "17": { displayName: "Custom Html" },
  "18": { displayName: "Team" },
  "19": { displayName: "Player" },
  "20": { displayName: "Press Release" },
  "21": { displayName: "PDF" },
  "22": { displayName: "Menu" },
  "23": { displayName: "Product" },
  "24": { displayName: "Institute" },
  "25": { displayName: "Player" },
  "26": { displayName: "File Type" },
  "27": { displayName: "Download Module" },
  "28": { displayName: "Casse Asset" },
  "29": { class: "item-type-podcast", displayName: "Audio" },
  "30": { displayName: "Author" },
  "31": { displayName: "Landing" },
  "32": { displayName: "Listing" },
  "33": { displayName: "Scorecard" },
  "34": { displayName: "Series" },
  "35": { displayName: "Bilateral Series" },
  "36": { displayName: "Job Profile" },
  "37": { displayName: "Data Page" },
  "38": { displayName: "Static Page" },
  "39": { displayName: "External Link" }
};
